### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by n0918k** [n0918k/furima-29211#11]
#URL https://frozen-sea-62554.herokuapp.com/
#Basic認証のIDとパスワード
ID:        n0918k
PASS:  6621
#出品者用のメールアドレスとパスワード
email:  1@1
pass:   ccc111
#購入者用のメールアドレスとパスワード
email:  2@2
pass:   ccc111
#購入用カードの番号・期限・セキュリティコード
4242424242424242
12 24
123

**Comment by kokikurahashi** [comment]
完了報告ありがとうございます！！
いつものコードレビューからではなく
https://docs.google.com/forms/d/e/1FAIpQLSe08G_NmjDTnmZwvplaR5dUh_zUdqH4B4T60lRDIGpzxqBJAg/viewform
こちらのフォームからご報告お願いいたします！！

**Comment by sho0127** [comment]
中川さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
 https://frozen-sea-62554.herokuapp.com/
にアクセスしたところ下記の表示が出ます。
<img width="1440" alt="スクリーンショット 2020-09-07 11 47 42" src="https://user-images.githubusercontent.com/68053333/92344043-51081680-f100-11ea-9937-d3129fe4fed0.png">


修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by n0918k** [comment]
修正しました

**Comment by sho0127** [comment]
中川さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
